### PR TITLE
Ignore .Rbuildignore files for install_local()

### LINKED ISSUE #107: Avoid copying .Rbuildignore files in install_local()
They may be huge, e.g., revdepcheck artifacts.

### PR DESCRIPTION
**Pull request by krlmlr**
Seems to work for me, but what kind of tests do we need here? Should this be used for other methods, such as installing from GitHub?

Fixes #107.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I think it is worth to have tests for the functions in rbuildignore.R.

**Comment by krlmlr** [comment]
Added tests for two low-level workers. No integration tests yet, do we need them?

**Comment by krlmlr** [comment]
@gaborcsardi: Would you mind taking another look? This is another minor pain when doing revdepchecks.

**Comment by gaborcsardi** [comment]
Can you pls import `setNames`?

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
I had to revert this, because it is causing problems: 

```
> remotes::install_local("s2_0.2-1.tar.gz", dependencies = TRUE, INSTALL_opts = "--build")
Error in normalizePath(target, winslash = "/", mustWork = TRUE) : 
  path[1]="/tmp/RtmpbFSWLk/filed25b209f8d//home/docker": No such file or directory
Calls: <Anonymous> ... remote_download -> remote_download.local_remote -> normalizePath
Execution halted
```

**Pull request merged**
