### PR TITLE
Initial support for git submodules

### PR DESCRIPTION
**Pull request by rtobar**
This initial support is based on the work done by @jonkeane for devtools, plus minor additions from my side. It includes submodules support for git2r, xgit and github remotes. It is not fully recursive yet, and the code is still not all cleanly separated, but it works as a first approach.

This pull request addresses #82.

### CODE REVIEW

**Comment by ronammar** [comment]
Thanks for this useful feature @rtobar and @jonkeane! Any idea when this code will be merged into master?

**Comment by rtobar** [comment]
No idea from my side. The pull request has been hanging out for a bit, but nothing much has happened since. Hopefully your comment will bring the attention back to this pull request.

**Comment by ronammar** [comment]
Bump?

**Comment by gaborcsardi** [comment]
Well, you said that:

> not fully recursive yet, and the code is still not all cleanly separated,

so I was wondering if you wanted to finish it.

**Comment by ronammar** [comment]
@rtobar - thoughts? I've been using your fork and it works recursively for me, so what functionality is absent?

**Comment by rtobar** [comment]
Hi @ronammar, @gaborcsardi 

When I say that it's not fully recursive I mean that submodules are not checked for submodules (e.g., repository A references repository B, which in turn references repository C), which IIRC hasn't been implemented yet. I didn't even try that scenario, so if it works it's pure chance. When you say that it works recursively for you, do you mean exactly that, or only that one level of submodule references works fine?

By the code not being cleanly separated I mean that the specifics about "recursiveness" are not generic enough at the moment since {{install-remotes.R}} has code that is specific to {{git}}-related remotes, instead of generalizing this concept and coding it into each of the supported remotes. As a first iteration it works though, which is why I though this request was maybe already good enough to be present as a first iteration.

If @gaborcsardi thinks this needs a bit more of work before being accepted I could try to find some time to address the comments, but can't promise any speedy delivery.

**Comment by ronammar** [comment]
@rtobar Admittedly, I've only tested with a single submodule level, so it behaved the same as a `git clone` recursive call for the same repo.

**Comment by ronammar** [comment]
Tested and it works for me. Thanks!

**Pull request closed without merging**
