### PR TITLE
Remove duplicate function definitions

### PR DESCRIPTION
**Pull request by krlmlr**
I haven't checked if the dupes are actually identical.

I wonder if there's a check for this kind of error. Shouldn't be too difficult to implement.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I don't understand this PR. Did you just auto-generate `install-github.R`?

**Comment by krlmlr** [comment]
`safe_install_packages()` and `missing_devel_warning()` are dupes already defined in `install.R` .

**Comment by gaborcsardi** [comment]
The file you modified is not part of the R package. It is only used for self-installing `remotes` and the `install-github.me` service.

**Comment by krlmlr** [comment]
Missed that part, sorry.

**Pull request closed without merging**
