### PR TITLE
Allow explicit package names in Remotes

### PR DESCRIPTION
**Pull request by heavywatal**
This package somehow manages differences in repo names vs package names. Ignoring the leading "pkgname=" part is enough to let this package work.

Addresses #676

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Great idea! I think we could make the implementation a bit safer by matching only something like `^[.a-zA-Z0-9]+=` instead of just a plain `=` which might appear in some remote specifications.

**Comment by gaborcsardi** [comment]
Great, thanks! Can you please also add a bullet point to `NEWS.md`, mentioning this PR (or the issue) and your GH username?

**Comment by heavywatal** [comment]
Done.

**Comment by gaborcsardi** [comment]
Thank you!

**Pull request merged**
