### PR TITLE
Convert warnings to errors when installing

### LINKED ISSUE #113: Install should fail if there's an error copying DLL on Windows
If a package is currently loaded on Windows and you try to install over it, some of the files will be copied over, but the DLL will not.

Real-world example here: hadley/scales#101

To reproduce:

```
> library(scales)
> remotes::install_github("hadley/scales")
Downloading GitHub repo hadley/scales@master
Installing package into ‘C:/Users/IEUser/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'scales' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/IEUser/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/IEUser/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c colors.cpp -o colors.o
c:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o scales.dll tmp.def RcppExports.o colors.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/i386 -lR
installing to C:/Users/IEUser/Documents/R/win-library/3.4/scales/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/IEUser/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/IEUser/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c colors.cpp -o colors.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o scales.dll tmp.def RcppExports.o colors.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lR
installing to C:/Users/IEUser/Documents/R/win-library/3.4/scales/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\scales.dll to C:\Users\IEUser\Documents\R\win-library\3.4\scales\libs\x64\scales.dll: Permission denied
** R
** preparing package for lazy loading
** help
Loading required package: scales
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (scales)
```

### PR DESCRIPTION
**Pull request by jimhester**
So this is a simple way to  fix #113, however it will only work for R 3.5.1-patched and up.

I guess the main question is should we only add the rprofile conditional on the R version, or just do it all the time even if it doesn't work except for newer versions of R.

### CODE REVIEW

**Comment by jimhester** [comment]
So I should actually switch to using the user R profile here, since the previous remotes behavior was using a blank user R profile.

**Comment by jimhester** [comment]
My only hesitation with that is making sure we get the logic on which user R profile is sourced correct.

But I guess it is really pretty straightforward

https://github.com/wch/r-source/blob/ff0bafa5dbbbfbac5f5ce386dbaf69eaf5506c90/src/gnuwin32/sys-win32.c#L40-L58

So sure we can do that.

**Comment by gaborcsardi** [comment]
`R_PROFILE_USER`, you mean,  right?

**Comment by jimhester** [comment]
Ok added logic to include the current user Rprofile as well.

Unfortunately it is hard to test this without having a version of R-devel handy. I guess I probably should install one though to test...

**Comment by jimhester** [comment]
Can confirm this works with R-devel as hoped

```
> library(glue) # to make sure we fail to install
> pkgbuild::with_build_tools(remotes::install_local("../glue_1.3.0.tar.gz"))
Running "C:/PROGRA~1/R/R-devel/bin/x64/Rcmd.exe" build \
  "C:\Users\IEUser\AppData\Local\Temp\RtmpiEPpFv\remotes1e082e93884\glue" --no-resave-data \
  --no-resave-data --no-manual --no-build-vignettes
* checking for file 'C:\Users\IEUser\AppData\Local\Temp\RtmpiEPpFv\remotes1e082e93884\glue/DESCRIPTION' ... OK
* preparing 'glue':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'glue_1.3.0.tar.gz'

Installing package into ‘C:/Users/IEUser/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'glue' ...
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c glue.c -o glue.o
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c trim.c -o trim.o
C:/RBuildTools/3.5/mingw_32/bin/gcc -shared -s -static-libgcc -o glue.dll tmp.def glue.o init.o trim.o -LC:/PROGRA~1/R/R-devel/bin/i386 -lR
installing to C:/Users/IEUser/Documents/R/win-library/3.6/glue/libs/i386

*** arch - x64
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c glue.c -o glue.o
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c trim.c -o trim.o
C:/RBuildTools/3.5/mingw_64/bin/gcc -shared -s -static-libgcc -o glue.dll tmp.def glue.o init.o trim.o -LC:/PROGRA~1/R/R-devel/bin/x64 -lR
installing to C:/Users/IEUser/Documents/R/win-library/3.6/glue/libs/x64
Error in file.copy(files, dest, overwrite = TRUE) : 
  (converted from warning) problem copying .\glue.dll to C:\Users\IEUser\Documents\R\win-library\3.6\glue\libs\x64\glue.dll: Permission denied
* removing 'C:/Users/IEUser/Documents/R/win-library/3.6/glue'
* restoring previous 'C:/Users/IEUser/Documents/R/win-library/3.6/glue'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\IEUser\Documents\R\win-library\3.6\00LOCK-glue\glue\libs\x64\glue.dll to C:\Users\IEUser\Documents\R\win-library\3.6\glue\libs\x64\glue.dll: Permission denied
Execution halted
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/IEUser/AppData/Local/Temp/RtmpiEPpFv/file1e08501a6543/glue_1.3.0.tar.gz’ had non-zero exit status
```

**Comment by gaborcsardi** [comment]
@jimhester 

So the problem is that we treat all warnings as errors, e.g. a non-existing `PACKAGES` file. From revdepcheck:

```r
Installing CRAN version of callr
Error: (converted from warning) unable to access index for repository https://bioconductor.org/packages/3.6/extra/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.6/extra/src/contrib/PACKAGES'
```

We could fix this in revdepcheck / remotes, but treating _all_ warnings as errors seems a bit too aggressive now.

**Comment by gaborcsardi** [comment]
Oh, wait, this was not merged yet?  I don't know what  is  going on then....

**Comment by jimhester** [comment]
I guess we could also set an error handler function we could use in `options(error =)`.

And then only cause an error for the specific dll copying issue, and convert all other errors (that are actually warnings) back to warnings?

Although I have a vague memory that you don't actually get the condition object in an error handler, only the message?

**Comment by gaborcsardi** [comment]
> Although I have a vague memory that you don't actually get the condition object in an error handler, only the message?

You don't get anything, you only get the error message from `getlasterror()`... You need to dig it out of the call stack....

**Comment by jimhester** [comment]
What a mess, I am not sure what to do then...

**Comment by gaborcsardi** [comment]
Maybe we could just fix the bioc repos issue, and still try to error....

**Comment by jimhester** [comment]
How are you getting that repo anyway in your repositories anyway?

Both `BiocInstaller::biocinstallRepos()` and `BiocManager::repositories()` do not return it for me when testing with R 3.4.3 and R 3.5.1.

**Comment by gaborcsardi** [comment]
Probably hardcoded, so yeah, we need to fix that anyway.

**Comment by jimhester** [comment]
Oh yeah, it looks like extra was removed / deprecated last year https://www.mail-archive.com/bioc-devel@r-project.org/msg07368.html, so maybe we should just remove it at https://github.com/r-lib/remotes/blob/50bca276bd3709014c3e9750489057d51c830704/R/bioc.R#L33 ?

**Comment by gaborcsardi** [comment]
Yeah, but for older bioc versions they still have it....

**Comment by jimhester** [comment]
Ok I can remove it conditional on the version then.

**Comment by jimhester** [comment]
Actually unless I am  missing I think they removed the extras repository entirely including older versions. I get 404s to all the versions e.g. https://bioconductor.org/packages/3.2/extra/

**Comment by gaborcsardi** [comment]
That link works fine for me.... it even contains 9 packages....

**Comment by jimhester** [comment]
Ok I now remove BiocExtras conditionally on the bioc version https://github.com/r-lib/remotes/commit/496787cfc4b0ff34f6622d3a0a42baa12c57f505

**Comment by jimhester** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
Well, still having issues  :( 👍 

```
 123#> setting R_REMOTES_STANDALONE to true
 124#> > remotes::install_local('pkgconfig_2.0.2.tar.gz',dependencies=TRUE,INSTALL_opts='--build')
 125#> Installing 5 packages: covr, digest, disposables, lazyeval, rex
 126#> Error: (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6:
 127#> cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6/PACKAGES'
 128#> Execution halted
```

and `http://www.stats.ox.ac.uk/pub/RWin` is a default repo, at least on some R versions.

So we either need to smartly catch these warnings, or  have an option to turn off the warning -> error conversion.

**Comment by gaborcsardi** [comment]
@jimhester fyi.

**Pull request merged**
