### PR TITLE
Allow for GITHUB_TOKEN to be detected in the environment configuration

### PR DESCRIPTION
**Pull request by coatless**
Modifies `github_pat()` by allowing for a list of aliases if `GITHUB_PAT` isn't detected. Most notably, checks for the 
presence of `GITHUB_TOKEN` in the environment.

### CODE REVIEW

**Comment by coatless** [comment]
The error being detected by the test suite is independent of this change based on the CI failing for other PRs with the same error:

> ── 1. Failure: install-github.R script is up to date (@test-script.R#15)  ──────
readLines(tmp) not equal to readLines(file.path(root, "install-github.R")).
Lengths differ: 5560 is not 5553

**Comment by jimhester** [comment]
Thanks for the PR!

In our workflow examples we set the `GITHUB_TOKEN` secret to the `GITHUB_PAT` environment variable [explicitly](https://github.com/r-lib/actions/blob/4fef3e012157302ad5012d6de16b64ac75d69386/examples/check-full.yaml#L40)

I think this is a better approach as even if we accepted this PR the `GITHUB_TOKEN` is a secret, not an environment variable. So you would still have to have a similar line in your workflow to set the `GITHUB_TOKEN` environment variable to enable it.

**Comment by coatless** [comment]
@jimhester thanks for the quick review. The change here isn't necessarily for the CI routine but is due to bringing `remotes` recognization up-to-par with `gh`'s recognized variables. In particular, `gh` provided support for both `GITHUB_TOKEN` and `GITHUB_PAT`: https://github.com/r-lib/gh/blob/74655c4b171cf9e5512278759b6b408619f904aa/R/gh_token.R#L257-L263

That said,`GITHUB_TOKEN` appears in some [428k+ code files on GitHub](https://github.com/search?q=GITHUB_TOKEN&type=Code) in comparison to `GITHUB_PAT`'s only [10K that uses](https://github.com/search?q=GITHUB_PAT&type=Code).

**Comment by jimhester** [comment]
Ok, makes sense, thanks again

**Pull request merged**
