### PR TITLE
Respect custom hosts

### PR DESCRIPTION
**Pull request by dagola**
In #448  a feature to specify a custom host URL in the Remotes field for e.g. enterprise GitHub or GitLab instances is requested.
This pull request adds a feature to specify the host URL explicitly:
```
<type>[@host]::<username>/<repo>[@ref]
```

The tests added may be not complete in the sense that I was not able to test against a custom host. Maybe anyone can provide some hints for better tests?

### CODE REVIEW

**Comment by dagola** [comment]
I also added a fix such that `ref`s with a slash are also allowed.

**Comment by dagola** [comment]
@jimhester  Any problems with this MR? Can I improve this MR somehow so it gets merged?

**Comment by jimhester** [comment]
Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by dagola** [comment]
@jimhester I added a bullet to NEWS but the automated checks fail because of the test `internal map is current` in `test-bioc.R` fails. Looks like there is a new `bioconductor` version.

**Comment by dagola** [comment]
@jimhester Anything else I can do?

**Comment by jimhester** [comment]
Thanks a watt!

**Comment by fabiandistlerkb** [comment]
That was really helpful, since I could not find it in the docs. Would you mind adding it, or point me to the place where this is documented? Especially the @host.name part was what I needed on ghe to make this work.

**Pull request merged**
