### PR TITLE
Install from GitLab repos with subgroups and dots in path

### PR DESCRIPTION
**Pull request by robertdj**
Fix for issues <https://github.com/r-lib/remotes/issues/420> and <https://github.com/r-lib/remotes/issues/259>

### CODE REVIEW

**Comment by robertdj** [comment]
The only test that fails is one in `test-script.R` that compares `install-github.R`. 
Should I just update the `install-gitlab` function in `install-github.R` or is there a special procedure?

**Comment by jimhester** [comment]
If you run `make` on the shell command line it will re-build the script for you.

**Comment by robertdj** [comment]
@jimhester : Do you need more from me in this PR?

**Comment by robertdj** [comment]
I'll update NEWS. 

I completely agree with the tests. I notice that the other GitLab tests use repositories on your GitLab account. Do you want to set up a repository within a subgroup and maybe one that has a dot in the name?

**Comment by ldecicco-USGS** [comment]
Do ya'll need more tests? We could really use this feature as we look into moving the USGS-R github organization into a subgroup of code.usgs.gov

The subgroup:
https://code.usgs.gov/water/stats

An example repo:
https://code.usgs.gov/water/stats/MGBT

For the record, this works:
```r
 remotes::install_git("https://code.usgs.gov/water/stats/MGBT.git")
 remotes::install_url("https://code.usgs.gov/water/stats/MGBT/-/archive/master/MGBT.zip")
```

**Comment by jimhester** [comment]
@ldecicco-USGS can you confirm this PR works for your setup? You can try it out by using `remotes::install_github("r-lib/remotes#424")`

**Comment by ldecicco-USGS** [comment]
Hmm...I might be doing this wrong:
```r
remotes::install_github("r-lib/remotes#424")
remotes::install_gitlab(repo = "water/stats/MGBT", host = "https://code.usgs.gov")
Error: Failed to install 'unknown package' from GitLab:
  cannot open URL 'https://code.usgs.gov/api/v4/projects/water%2Fstats/repository/files/MGBT%2FDESCRIPTION/raw?ref=master'
```

I also get:
```r
remotes::install_gitlab("r-lib-grp/my-awesome-group/test.pkg")
Error: Failed to install 'unknown package' from GitLab:
  cannot open URL 'https://gitlab.com/api/v4/projects/r-lib-grp%2Fmy-awesome-group/repository/files/test.pkg%2FDESCRIPTION/raw?ref=master'
```
BUT!
if I install from @robertdj 's PR:
```r
remotes::install_github("robertdj/remotes@feature/gitlab-id", force = TRUE)
remotes::install_gitlab(repo = "water/stats/MGBT", host = "https://code.usgs.gov", force = TRUE)
...
* DONE (MGBT)
```
Success!

**Comment by jimhester** [comment]
Are you restarting R between installing remotes?

**Comment by jimhester** [comment]
Great work, this package is now better thanks to you!

Thanks!! You are da bomb!

**Pull request merged**
