### PR TITLE
Use HTTPS for security

### PR DESCRIPTION
**Pull request by ankane**
🔒

### CODE REVIEW

**Comment by gaborcsardi** [comment]
The problem with this is that some older R builds do not support HTTPS. Typically R 3.1.x, which we still want to support.

**Comment by ankane** [comment]
What do you think of a conditional approach, where >= 3.2 uses HTTPS?

**Comment by gaborcsardi** [comment]
Yes, but we would need to condition on actual HTTPS support. Or libcurl. This is with HTTPS support:
```
> capabilities("libcurl")
libcurl
   TRUE
```

Without can be FALSE, or even:
```
> capabilities("libcurl")
named logical(0)
```

**Comment by gaborcsardi** [comment]
Although windows will support HTTPS  w/o libcurl, but AFAIR newer windows builds also link to libcurl, so it might be ok to ignore that.

**Comment by ankane** [comment]
Cool, made it conditional on libcurl.

**Comment by jimhester** [comment]
Unfortunately whether a given download method is secure is more complicated than just checking if R is compiled with libcurl support. Even in that case they could not be using libcurl and using a download method that is not insecure. Devtools has the following to determine if a download method is secure.

See the [devtools/R/download-method.R](https://github.com/r-lib/devtools/blob/26c507b128fdaa1911503348fedcf20d2dd30a1d/R/download-method.R).

**Comment by gaborcsardi** [comment]
I think it is ok if we miss some. In practice  most new R builds will default to libcurl, and HTTPS will be probably fine for these.

**Comment by gaborcsardi** [comment]
We could also copy over that logic from devtools.

**Comment by ankane** [comment]
Updated PR based on your feedback @jimhester

**Comment by gaborcsardi** [comment]
I think this is good. @jimhester ?

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
